[package]
name = "selphy-cli"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[[bin]]
name = "selphy"
path = "src/main.rs"

[dependencies]
selphy = { workspace = true, features = ["clap"] }
anyhow.workspace = true
clap.workspace = true
indicatif.workspace = true
inquire.workspace = true

[dev-dependencies]
selphy = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
